name: Build and Upload Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Adjust to your Go version

      # Build the binary
      - name: Build binary
        run: |
          go build -o new-callings-parser

      # Upload the binary as an artifact
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: new-callings-parser
          path: new-callings-parser